language: node_js

node_js:
  - 10

cache:
  yarn: true
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
      - python3
      - python3-dev
      - python3-pip

before_install:
  - travis_retry yarn global add gulp@4 standard@12

  - travis_retry wget https://github.com/HelloZeroNet/ZeroNet/archive/py3/ZeroNet-py3.tar.gz
  - tar xvpfz ZeroNet-py3.tar.gz
  - cd ZeroNet-py3 && travis_retry pip3 install --user -r requirements.txt && cd ..
  - mv ZeroNet-py3 /tmp/zeronet

install:
  - travis_retry yarn install

script:
  - yarn lint

after_success:
- |
  if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]
  then
    yarn deploy --zeronet=/tmp/zeronet --privkey=${ZERONET_PRIVKEY} | sed 2d
  fi
